# -*- coding: utf-8 -*-
"""PC3 Grupo A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uLguK-0Wq_NXpjPnydRdADejpFm6HbGe
"""

import requests

url = "https://books.toscrape.com/"
response = requests.get(url)

print(f"verifiación  del request {response.status_code}")
# un salida 200 indica que el request fue exitoso



